### ISSUE TITLE
Solidity `hex""` should be represented as `bytes`, not `bytes1`

### ISSUE THREAD

**Issue by plotchy** [nascentxyz/pyrometer#39]
This has implications when using low level calls and trying to hit fallbacks or receives

```js
contract A {

    function foo() public {
        address a = address(0);
        a.call(hex"");
        a.delegatecall(hex"");

        bytes memory data = hex"01234567";
    }
}
```
Notice that member access is looking for `call(bytes1)` and `delegatecall(bytes1)`
<img width="536" alt="image" src="https://github.com/nascentxyz/pyrometer/assets/98172525/fa3830de-eadc-4a55-9088-4a7351554246">

**Comment by plotchy** [comment]
Actually this gets weird. All are valid solidity. Would recommend bytes as default

```js
contract A {

    function foo() public {
        bytes1 a = hex"";
        bytes2 b = hex"";
        bytes3 c = hex"";
        bytes4 d = hex"";
        bytes memory e = hex"";
    }
}
```

**Comment by brockelmore** [comment]
It is because we are trying to do type inference from a literal to a specified target type (we have to do this basically), but it gets tricky for function calls because we have to deduce what function we are actually calling (i.e. disambiguate the function). Should be trivial for `call` and builtins to get this right though.

**Comment by plotchy** [comment]
Makes sense. Solidity won't compile with this. Hard for us as we're not trying to enforce valid solidity.

<img width="686" alt="image" src="https://github.com/nascentxyz/pyrometer/assets/98172525/609b0d10-8219-4bb0-a7de-fb6ae3a1916b">
